name: Run MATLAB
on: [push]
jobs:
  my-job:
    strategy:
      matrix:
        platform: [windows-latest]
        release: [latest]
  
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
#       - name: Cache MATLAB
#         id: cache-matlab
#         uses: actions/cache@v3
#         with:
#           path: ${{ runner.tool_cache }}/MATLAB
#           key: ${{ matrix.platform }}-${{ matrix.release }}
      # - name: Setup MATLAB
      #   uses: matlab-actions/setup-matlab@v2
      #   with:
      #     release: ${{ matrix.release }}
      #     products: MATLAB
      - run: echo $PATH
      - name: Get run-matlab-command
        run: sudo wget -O /usr/bin/run-matlab-command https://ssd.mathworks.com/supportfiles/ci/run-matlab-command/v1/glnxa64/run-matlab-command
      - name: Run MATLAB Command
        run: run-matlab-command "disp('hello world')"
