name: Run MATLAB
on: [push]
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: version
