name: Run MATLAB
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with:
          startup-options: -sd subfolder
          test-results-junit: myresults.xml
          use-parallel: true
      - run: ls *
