name: Run MATLAB
on:
  workflow_dispatch: {}
  push: {}
jobs:
  my-job:
    runs-on: macos-14
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: Simulink
          cache: true
          release: latest
      - name: Run command
        run: |
          wget https://ssd.mathworks.com/supportfiles/ci/run-matlab-command/v2/maca64/run-matlab-command
          chmod +x run-matlab-command
          ./run-matlab-command "disp('hello world')" &
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
