name: Run MATLAB
on:
  workflow_dispatch: {}
  push: {}
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest
      - name: Run MATLAB Command
        uses: matlab-actions/run-command@v2
        with:
          command: version
